config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :articles do
    resources :votes, only: %i[create destroy]
  end
  resources :categories, except: %i[edit update destroy]
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'my_favorites', to: 'articles#favorites'
end

app/models/article.rb
class Article < ApplicationRecord
  before_save { self.title = title.capitalize if title }

  belongs_to :author, class_name: 'User'
  belongs_to :category
  has_many :votes, dependent: :destroy
  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }

  has_one_attached :image
  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :text, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :category_id, presence: true

  scope :order_by_created, -> { order(created_at: :desc) }
  scope :latest16, -> { limit(16) }
  scope :latest, -> { order(created_at: :desc).limit(1).first }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: %i[index]
  before_action :set_article, only: %i[show edit update destroy]
  before_action only: %i[edit update destroy] do
    require_same_user(@article.author)
  end

  def index
    @articles = Article.includes(:votes).order_by_created.latest16
  end

  def favorites
    target_article_ids = Vote.where(user_id: current_user.id).pluck(:article_id)
    @articles = Article.includes(:votes).where(id: target_article_ids)
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.author_id = current_user.id

    if @article.save
      flash[:notice] = "#{@article.title} was successfully created"
      redirect_to @article
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:notice] = "#{@article.title} was successfully updated"
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "#{@article.title} was successfully deleted"
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :category_id, :image)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def articles_image(article)
    if article.image.exists?
      image_tag(article.image.url, class: 'articles__image')
    else
      image_tag('no_img.jpg', class: 'articles__image')
    end
  end

  def voted_star(article)
    if login? && current_user.already_voted?(article.id)
      link_to(article_vote_path(article_id: article.id,
                                id: find_vote_id(article.id)), method: :delete, class: 'articles__star') do
        content_tag(:i, nil, class: 'fas fa-star')
      end
    else
      link_to(article_votes_path(article), method: :create, class: 'articles__star') do
        content_tag(:i, nil, class: 'far fa-star')
      end
    end
  end

  def my_favorites_articles(articles)
    if articles.any?
      content_tag(:div, class: 'articles') do
        render articles
      end
    else
      render 'shared/notfound'
    end
  end

  def all_articles(articles)
    if articles.any?
      content_tag(:div, class: 'articles') do
        render articles
      end +
        content_tag(:div, class: 'btns') do
          link_to('Create a new article', new_article_path, class: 'btn btn-info')
        end
    else
      render 'shared/notfound'
    end
  end

  def single_article_image(article)
    image_tag(article.image.url, class: 'article__thumb') if article.image.exists?
  end

  def edit_btns_for_single_post(article)
    return if current_user != article.author

    content_tag(:div, class: 'btns') do
      link_to('Edit', edit_article_path(article), class: 'btn btn-info') +
        link_to('Delete', article_path(article), method: :delete,
                                                 data: { confirm: 'Are you sure?' }, class: 'btn btn-danger')
    end
  end

  def current_image_thumb(article)
    return unless article.image.exists?

    image_tag(article.image.url(:thumb), class: 'field__thumb')
  end
end

app/views/articles/_article.html.erb
<article class="articles__item">

  <div class="articles__images">
    <%= articles_image(article) %>
  </div>

  <div class="articles__texts">
    <div class="articles__category">
        <span><%= link_to article.category.name, category_path(article.category) %></span>
    </div>
    <h2 class="articles__title"><%= article.title %></h2>
    <div class="articles__author">Posted by <%= link_to article.author.name, user_path(article.author), class: "articles__author__link" %></div>
    <div class="articles__date">&mdash; Posted <%= distance_time(article.created_at) %> ago</div>
    <div class="articles__excerpt">
      <%= excerpt(article.text) %>
    </div>
    <%= link_to 'Read more', article_path(article), class: "articles__readmore" %>
  </div>

  <div class="articles__vote">
    <%= voted_star(article) %>
    <span class="articles__star__num"><%= votes_size(article.id)  %></span>
  </div>
</article>

app/views/articles/_form.html.erb
<%= render  "shared/errors", obj: article %>
<%= form_with model: article, multipart: true do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>

  <div class="field">
    <%= f.label :category_id, "Select Category" %>
    <%= f.collection_select :category_id, Category.order(:priority), :id, :name, include_blank: true %>
  </div>

  <div class="field">
    <%= current_image_thumb(@article) %>
    <%= f.label :image, "Attach a New Image" %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit class: "btn btn-info" %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an article</h1>
<%= render "form", article: @article %>

app/views/articles/favorites.html.erb
<h1>My favorites' articles</h1>
<%= my_favorites_articles(@articles) %>

app/views/articles/index.html.erb
<%= all_articles(@articles)  %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="article">
  <%= single_article_image(@article) %>

  <h1 class="article__title"><%= @article.title %></h1>
  <div class="article__category">
    <span><%= @article.category.name %></span>
  </div>

  <div class="article__author">Posted by <%= link_to  @article.author.name, user_path(@article.author) %></div>
  <div class="article__date">&mdash; Posted <%= distance_time(@article.created_at) %> ago</div>

  <div class="article__text">
    <%= @article.text %>
  </div>

  <%= edit_btns_for_single_post(@article)  %>
</div>