config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :articles do
    resources :votes, only: %i[create destroy]
  end
  resources :categories, except: %i[edit update destroy]
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'my_favorites', to: 'articles#favorites'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy, foreign_key: :author_id
  has_many :votes, dependent: :destroy
  REGEX_FOR_NAME = /\A[a-zA-Z0-9_]+\z/.freeze
  msg = "can user only letters, numbers and underscores '_'"
  validates :name, presence: true, length: { minimum: 3, maximum: 30 },
                   uniqueness: true, format: { with: REGEX_FOR_NAME, message: msg }

  def already_voted?(article_id)
    votes.find_by(article_id: article_id) ? true : false
  end

  def ordered_articles
    articles.includes(:votes).order_by_created
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: %i[new create]
  before_action :set_user, only: %i[show edit update destroy]
  before_action only: %i[edit update destroy] do
    require_same_user(@user)
  end

  def index
    @users = User.includes(%i[articles votes])
  end

  def show
    @articles = @user.ordered_articles
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.name} was successfully created and logged in"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = "#{@user.name} was successfully updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    flash[:notice] = "#{@user.name} was successfully deleted and logged out"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def all_users(users)
    return unless users.any?

    content_tag(:div, class: 'users') do
      render(partial: 'user', collection: users)
    end
  end

  def account_settings(user)
    return if current_user != user

    content_tag(:div, class: 'my-settings') do
      content_tag(:div, 'Account Settings', class: 'my-settings__title') +
        content_tag(:div, class: 'btns my-settings__btns') do
          link_to('My favorites', my_favorites_path, class: 'btn btn-standout') +
            link_to('Edit Name', edit_user_path(user), class: 'btn btn-info') +
            link_to('Delete My Account', user_path(user), method: :delete,
                                                          data: { confirm: 'Are you sure to delete this user?' },
                                                          class: 'btn btn-danger')
        end
    end
  end

  def users_articles(articles)
    if articles.any?
      content_tag(:div, class: 'articles') do
        render(partial: 'articles/article', collection: @articles)
      end
    else
      render 'shared/notfound'
    end
  end
end

app/views/users/_form.html.erb
<%= render  "shared/errors", obj: user %>
<%= form_with model: user do |f| %>
  <div class="field">
    <%= f.label :name, "Enter your name" %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit class:"btn btn-info" %>
<% end %>

app/views/users/_user.html.erb
<div class="users__item">
  <%= link_to  user.name, user_path(user) %>
</div>

app/views/users/edit.html.erb
<h1>Edit User's name</h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>All Users</h1>
<%= all_users(@users)  %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", user: @user %>
<div class="btns center note">
  <small>If you have your account already, you can <%= link_to "log in", login_path %></small>
</div>

app/views/users/show.html.erb
<%= account_settings(@user)  %>
<h1><%= @user.name %>'s articles</h1>
<%= users_articles(@articles)  %>