config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :articles do
    resources :votes, only: %i[create destroy]
  end
  resources :categories, except: %i[edit update destroy]
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'my_favorites', to: 'articles#favorites'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer__container">
    <%= link_to root_path, class: "footer__logo logo" do %>peTs sTyLe <%= icon('fas', 'paw') %><% end %>
    <div class="footer__content">
      <ul class="footer__list">
          <li class="footer__item"><%= link_to "Privacy Policy", '#', class: "footer__link" %></li>
          <li class="footer__item"><%= link_to "Terms & Conditions", '#', class: "footer__link" %></li>
      </ul>
      <div class="footer__copy">Copyright <%= this_year %>. All rights reserved.</div>
    </div>
    <div class="footer__sns">
      <span class="footer__sns__note">Connect with us :</span>
      <div class="footer__sns__links">
        <%= link_to "#", class:'footer__sns__link' do %><%= icon('fab', 'twitter') %><% end %>
        <%= link_to "#", class:'footer__sns__link' do %><%= icon('fab', 'instagram') %><% end %>
        <%= link_to "#", class:'footer__sns__link' do %><%= icon('fab', 'facebook-f') %><% end %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header__head">
    <%= link_to root_path, class: "header__logo logo" do %>peTs sTyLe <%= icon('fas', 'paw') %><% end %>
    <nav class="header__nav">
      <ul class="header__nav__list">
        <li class="header__nav__item"><%= link_to  "Home", root_path, class: header_home_class %></li>
        <li class="header__nav__item"><%= link_to  "Write an article", new_article_path, class: header_new_article_class %></li>
        <li class="header__nav__item"><%= link_to  "All Articles", articles_path, class: header_all_article_class %></li>
        <%= header_menu_for_login_user %>
      </ul>
      <ul class="header__nav__list">
        <%= login_logout_menu  %>
      </ul>
    </nav>
    <%= link_to '#', class: "header__search" do %><%= icon('fas', 'search') %><% end %>
    <div id="toggle__button" class="toggle__button">
      <span class="toggle__span"></span>
      <span class="toggle__span"></span>
      <span class="toggle__span"></span>
    </div>
  </div>


    <div class="sidemenu" id="sidemenu">
      <nav class="sidemenu__nav">
        <ul class="sidemenu__list upcase">
          <li class="sidemenu__item">
            <%= link_to "Home", root_path, class: side_home_class %>
          </li>
          <li class="sidemenu__item">
            <%= link_to "Write an Article", new_article_path, class: side_new_article_class %>
          </li>

          <%= side_category_menu %>
          <%= sidemenu_for_not_login_user  %>
        </ul>
      </nav>
      <%= sidemenu_for_login_user  %>
    </div>
</header>

app/views/layouts/_messages.html.erb
<%= flash_messages(flash) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pets Magazine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'custom/custom' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
        <%= render "layouts/messages" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>